add service doc
swiss-ai-center/documentation pull request #106
Opened 2024-07-24 09:28 UTC by JonathanGuerne

2024-07-24 09:36 UTC, JonathanGuerne commented
I noticed that the staging url (https://class-rebalancing-swiss-ai-center.kube.isc.heia-fr.ch) seems to link to an unrelated page (about a pet clinic), if that is a mistake on my part let me know

2024-07-24 09:45 UTC, andrptrc commented
> I noticed that the staging url (https://class-rebalancing-swiss-ai-center.kube.isc.heia-fr.ch) seems to link to an unrelated page (about a pet clinic), if that is a mistake on my part let me know

Try to run the Workflow again if you check the last run in the Action section you can see that the service has not been deployed.

2024-07-24 14:07 UTC, rmarquis commented
The deployment should happen only for documentation in the main branch (as per the workflow deploy condition).
I feel there's an hidden story about that pet clinic, but I'm afraid to ask haha.

2024-07-24 14:08 UTC, rmarquis requested changes

2024-07-24 14:08 UTC, rmarquis commented on docs/reference/index.md
> +| [class-rebalancing](./services/class-rebalancing.md)     | <https://github.com/swiss-ai-center/class-rebalancing-service>   | <https://class-rebalancing-swiss-ai-center.kube.isc.heia-fr.ch>   | <ht
Nitpicking here, but can we have proper spacing to get a nicer alignment? That might ease future review of that table.

2024-07-24 14:29 UTC, rmarquis commented on docs/reference/index.md
> +| [class-rebalancing](./services/class-rebalancing.md)     | <https://github.com/swiss-ai-center/class-rebalancing-service>   | <https://class-rebalancing-swiss-ai-center.kube.isc.heia-fr.ch>   | <ht
Nvm, I fixed it and cleaned the rest of the table too.

2024-07-24 14:30 UTC, rmarquis approved these changes

2024-07-24 14:30 UTC, merged

2024-07-24 14:38 UTC, rmarquis commented
@JonathanGuerne For the service deploiement, maybe check you correctly set the environment variables in settings (I don't seem to have access to the settings of that repo).

2024-07-25 09:33 UTC, JonathanGuerne commented
@rmarquis I followed your advice and made sure the env variable were correctly set. (also you should have access now)

The dev deployment is working (I tested the service already), only the api-doc url mention above still redirect to the wrong ressource for now

2024-07-25 10:09 UTC, rmarquis commented
This looks like an issue on the dev cluster to me. As far as I remember, there is no explicit special configuration needed for the docs rediction URL. The docs is correctly [available online](https://class-rebalancing-swiss-ai-center.kube.isc.heia-fr.ch/docs), only the redirect is not configured properly.

I've deployed a service just a 2 weeks ago, without any issue. I have no explanation here.
Maybe try to deploy in production, and check that the docs redirection behaves as expected? If it does, this might be a sign of a recent misconfiguration on the dev cluster.

2024-07-25 10:13 UTC, andrptrc commented
> @rmarquis I followed your advice and made sure the env variable were correctly set. (also you should have access now)
> 
> The dev deployment is working (I tested the service already), only the api-doc url mention above still redirect to the wrong ressource for now

Which link exactly is not working?

2024-07-25 10:57 UTC, JonathanGuerne commented
This one: https://class-rebalancing-swiss-ai-center.kube.isc.heia-fr.ch/

2024-07-25 11:16 UTC, andrptrc commented
> This one: https://class-rebalancing-swiss-ai-center.kube.isc.heia-fr.ch/

It seems to work for me, It shows the Swagger API, what does it show to you ?

2024-07-25 11:21 UTC, JonathanGuerne commented
It redirects me to this url: https://class-rebalancing-swiss-ai-center.kube.isc.heia-fr.ch/petclinic/ (a landing page for a pet clinic apparently)

2024-07-25 11:22 UTC, andrptrc commented
> It redirects me to this url: https://class-rebalancing-swiss-ai-center.kube.isc.heia-fr.ch/petclinic/ (a landing page for a pet clinic apparently)

Did you try to clear your cache and cookies ? This page is the default page for nginx I guess and for me it redirects correctly

2024-07-25 11:24 UTC, JonathanGuerne commented
You're right, it worked ^^'
thanks and sorry for that

2024-07-25 11:25 UTC, andrptrc commented
No problem glad to help 😉